# Generated by Django 4.0.5 on 2022-06-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fav_color',
            new_name='github_id',
        ),
    ]
