# Generated by Django 4.0.5 on 2022-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_fav_color_customuser_github_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
